name: Deploy
on:
  push:
    branches:
      - main
      - staging

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deployment workflow
    - run: |
        gh api --method POST \
          -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/ipshipyard/waterworks-infra/dispatches \
          -f "event_type=deploy" \
          -F "client_payload[git_sha]=${GITHUB_SHA}" \
          -F "client_payload[git_ref]=${GITHUB_REF}"
      env:
        GH_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_PAT }}
